
x = 10
try:
    print(x)
except:
    print("An error has occured")
else:
    print("Something went wrong")
finally:
    print("The 'try except' is finished")
